/*globals define*/
/*jshint node:true, browser:true*/

/**
 * Generated by PluginGenerator 1.7.0 from webgme on Sun Nov 27 2016 19:39:42 GMT-0600 (Central Standard Time).
 * A plugin that inherits from the PluginBase. To see source code documentation about available
 * properties and methods visit %host%/docs/source/PluginBase.html.
 */

define([
    'plugin/PluginConfig',
    'text!./metadata.json',
    'plugin/PluginBase',
    'plugin/XMIExporter/XMIExporter/XMIExporter',
    'q'
], function (
    PluginConfig,
    pluginMetadata,
    PluginBase,
    XMIExporter,
    Q) {
    'use strict';

    pluginMetadata = JSON.parse(pluginMetadata);

    /**
     * Initializes a new instance of PythonPlugin.
     * @class
     * @augments {PluginBase}
     * @classdesc This class represents the plugin PythonPlugin.
     * @constructor
     */
    var PythonPlugin = function () {
        // Call base class' constructor.
        PluginBase.call(this);
        this.pluginMetadata = pluginMetadata;
    };

    /**
     * Metadata associated with the plugin. Contains id, name, version, description, icon, configStructue etc.
     * This is also available at the instance at this.pluginMetadata.
     * @type {object}
     */
    PythonPlugin.metadata = pluginMetadata;

    // Prototypical inheritance from PluginBase.
    PythonPlugin.prototype = Object.create(PluginBase.prototype);
    PythonPlugin.prototype.constructor = PythonPlugin;

    /**
     * Main function for the plugin to execute. This will perform the execution.
     * Notes:
     * - Always log with the provided logger.[error,warning,info,debug].
     * - Do NOT put any user interaction logic UI, etc. inside this method.
     * - callback always has to be called even if error happened.
     *
     * @param {function(string, plugin.PluginResult)} callback - the result callback
     */
    PythonPlugin.prototype.main = function (callback) {
        var self = this,
            languageName = self.core.getAttribute(self.rootNode, 'name'),
            fName = languageName + '.xml';

        XMIExporter.getXMLStr(self, '__')
            .then(function (xmlStr) {
                var fs = require('fs');
                return Q.ninvoke(fs, 'writeFile', fName, xmlStr);
            })
            .then(function () {
                var exec = require('child-process-promise').exec;
                return exec('python src/plugins/PythonPlugin/PythonPlugin.py ' + fName);
            })
            .then(function (result) {
                var stdout = result.stdout;

                if (stdout) {
                    self.createMessage(null, stdout);
                    self.result.setSuccess(true);
                }

                callback(null, self.result);
            })
            .catch(function (err) {
                self.logger.error(err.stack);
                callback(err, self.result);
            });

    };

    return PythonPlugin;
});
